apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 100-sno-kernelargs 
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
      - amd_iommu=on 
      - vga=off
      - rdblaclist=nouveau
      - 'video=efifb:off'
