apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 98-sno-xhci-unbind
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - contents: |
         [Unit]
         Description=Unbind USB Host Controller Driver
         After=ignition-firstboot-complete.service
         Before=kubelet.service crio.service

         [Service]
         Type=oneshot
         ExecStart=/bin/bash -c "/bin/echo 0000:0b:00.3 > /sys/bus/pci/devices/0000\\:0b\\:00.3/driver/unbind"
         ExecStart=/bin/bash -c "/bin/echo vfio-pci > /sys/bus/pci/devices/0000\\:0b\\:00.3/driver_override"
         ExecStart=/bin/bash -c "/bin/echo 1043 87c0 > /sys/bus/pci/drivers/vfio-pci/new_id"

         [Install]
         WantedBy=kubelet.service
        enabled: true
        name: unbindusbcontroller.service
