---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: fedora001
  labels:
    vol: fedora001
spec:
  capacity:
    storage: 30Gi
  local:
    path: /dev/localvolumes/fedora001
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Block
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - da2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fedora001
  labels:
    vol: fedora001
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 30Gi 
  storageClassName: local-storage
