apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 98-dettach-vtconsole
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - contents: |
         [Unit]
         Description=Dettach GPU VT Console 
         After=ignition-firstboot-complete.service
         Before=kubelet.service crio.service

         [Service]
         Type=oneshot
         ExecStart=/bin/bash -c "/bin/echo 0 > /sys/class/vtconsole/vtcon0/bind"

         [Install]
         WantedBy=kubelet.service
        enabled: true
        name: dettachvtconsole.service
