apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    description: Local Disks
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
