apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos001
  namespace: epheo
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos001
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: pvdisk
            - bootOrder: 2
              disk:
                bus: virtio
              name: pvdisk2
          interfaces:
            - masquerade: {}
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        resources:
          requests:
            memory: 4G
      hostname: centos001
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
        - persistentVolumeClaim:
            claimName: 'centos'
          name: pvdisk
        - persistentVolumeClaim:
            claimName: 'lindata'
          name: pvdisk2
